title = "Shankar Nakai Gon√ßalves dos Santos"
languageCode = "en-us"
baseurl = "http://shankarnakai.github.io/"
canonifyurls: true
publishdir: "public"

[author]
  name = "Your Name"
  email = ""
  
  github = ""
  twitter = ""
  facebook = ""
  googleplus = ""
  linkedin = ""
  gaID = "Google Analytics Tracking ID"

[params]
  Description = "text under logo"
  # Optional
  disqusShortname = ""
  highlight_theme = "tomorrow-night"
  notoc = true


# Optional sections:
[permalinks]
  posts = "/:year/:month/:filename/"

[blackfriday]
  plainIdAnchors = true
